### PR TITLE
Sample query: GET member in a chat

### PR DESCRIPTION
**Pull request by ayubun**
AD#37906

Add a sample query to get a member that exists in a chat

### CODE REVIEW

**Comment by ayubun** [comment]
I noticed some of the queries have helpful tips on how to acquire the IDs necessary to run them. It would be useful to write up a tip for this one as well.

**Comment by ayubun** [comment]
Tested by @gracet9182 - Permissions are still missing for chat queries;

Awaiting the permissions fix from @jerryxihe / @anneguo3. Unknown ETA 👀

**Comment by gracet9182** [comment]
Bettirose emailed Michael Mainer this morning. They're looking into providing the permission for "ChatMember.Read...regarding the user with the id: d4957c9d-869e-4364-830c-d0c95be72738".

**Comment by gracet9182** [comment]
Michael granted us permissions! @AyuAi You can run the get chat query and test this out now. I picked an arbitrary chat id 

Screenshot 2021-07-13 081520

**Comment by ayubun** [comment]
> Michael granted us permissions! @AyuAi You can run the get chat query and test this out now. I picked an arbitrary chat id
> 
> Screenshot 2021-07-13 081520

Omg ily TY

**Comment by ayubun** [comment]
Merging to `interns/feature/new-sample-queries` to expedite + organization purposes! PR for such is incoming.

**Pull request merged**
